services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - tig-benchmarker
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  master:
    build:
      context: ./
      dockerfile: ./master/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - VERBOSE=${VERBOSE}
    networks:
      - tig-benchmarker
    ports:
      - ${MASTER_PORT}:5115
    expose:
      - 3336
    depends_on:
      db:
        condition: service_healthy

  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - tig-benchmarker
    expose:
      - 80
    depends_on:
      - master

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${UI_PORT}:80"
    networks:
      - tig-benchmarker
    depends_on:
      - ui
      - master

networks:
  tig-benchmarker:

volumes:
  pgadmin-data:
